spring.datasource.url=jdbc:mysql://localhost:3306/traffic_db
spring.jpa.open-in-view=false
spring.datasource.username=root
spring.datasource.password=rudra123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin123